image: node:14.16.0

test:
  stage: test
  image: cypress/browsers:node14.16.0-chrome89-ff86
  variables:
    # Use polling watcher to avoid error:
    #   Error from chokidar (...): Error: ENOSPC: System limit for number of file watchers reached, watch '...'
    # (this despite the fact that react-scripts shouldn't be watching at all when CI=true, as it is here)
    # https://create-react-app.dev/docs/advanced-configuration/
    CHOKIDAR_USEPOLLING: "true"
  script:
    - yarn install --immutable --immutable-cache
    - yarn run cypress install
    - yarn run cypress verify
    - yarn run cypress info
    - yarn run tsc
    - yarn run build-storybook
    - yarn test-storybook
    - "yarn cy:run"
