# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - uses: actions/checkout@v2

      - name: yarn
        run: yarn install --immutable --immutable-cache

      - name: tsc
        run: yarn run tsc

      - name: build storybook
        run: yarn run build-storybook

      - name: test (storybook)
        run: yarn test-storybook

      - name: test (default cypress suite)
        run: yarn cy:run
