name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86

    steps:
      - uses: actions/setup-node@v2.1.5

      - uses: actions/checkout@v2

      - name: yarn
        run: yarn install --immutable --immutable-cache

      - name: cypress info
        run: |
          yarn run cypress install
          yarn cy:verify
          yarn cy:info

      - name: tsc
        run: yarn run tsc

      - name: build storybook
        run: yarn run build-storybook

      - name: test (storybook)
        run: yarn test-storybook

      - name: test (default cypress suite)
        run: yarn cy:run
