name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      env:
        # Use polling watcher to avoid error:
        #   Error from chokidar (...): Error: ENOSPC: System limit for number of file watchers reached, watch '...'
        # (this despite the fact that react-scripts shouldn't be watching at all when CI=true, as it is here)
        # https://create-react-app.dev/docs/advanced-configuration/
        CHOKIDAR_USEPOLLING: "true"

    steps:
      - uses: actions/setup-node@v2.1.5

      - uses: actions/checkout@v2

      - name: yarn
        run: yarn install --immutable --immutable-cache

      - name: cypress info
        run: |
          yarn run cypress install
          yarn run cypress verify
          yarn run cypress info

      - name: tsc
        run: yarn run tsc

      - name: build storybook
        run: yarn run build-storybook

      - name: test (storybook)
        run: yarn test-storybook

      - name: test (default cypress suite)
        run: yarn cy:run
